sudo: required

language: node_js

node_js: "8"

services:
  - docker

install: true

script:
  - docker build --tag johnnyreilly/poorclares .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master