version: '2.1'

services:
  poor-clares-arundel-koa:
    image: poor-clares-arundel-koa
    build: .
    environment:
      NODE_ENV: production
      APPSETTINGS_API_KEY: 'this is the guid from mailgun'
      APPSETTINGS_DOMAIN: 'mg.priou.co.uk'
      APPSETTINGS_PRAYER_REQUEST_FROM_EMAIL: 'noreply@mg.priou.co.uk'
      APPSETTINGS_PRAYER_REQUEST_RECIPIENT_EMAIL: 'info@priou.co.uk'
    ports:
      - 3000:3000